language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: bJWoqoR5RCagChbDi7e3nn+kLVv2TnrdZWsHMqvtHtciLcZva6y6Oh9C6QJZhUeyhYT+x0j/nXX5qmDzU2zfnG/eZcEhkPmt9sJriAHp9cEFd7iqtiMiQ7RCn11ULTv0/ib8kepul1j88y3xsyZJpqBxYVzjrd1gDVZyHgN9354FDjL1q0PB1huA2aq+jsqNrUzhaKqO0NZldt9HszOnC/OtbDbkMjh3RBYDmqsaZHOLeAhoOf8lzunRHgCHD3O/8KXjRWbpnGi29FMlkpQWT/Wscc9fXXutj86t6znEv/bm0ebn8mfKqGdKkC2M4e5KD1bd/rAGuSB37bbYwNTQLgLnlm4lSQsFBB5rRTWrC/2jAJwvYm8ALuj4k63EdYNrFD5PJSPRVYqJWVAIMtv3CqHMwkg+ah1qiRLh0dH4lJcleuGunEG0jsHO6X/xWYdt2V1Qc6nuuDYMujx0Brh4n3EOd3nKHSBMbbv3L+U96ZBqISK0nCTuPCWWbZ7uk21bv8fesn7egTmKMZmeHWIYj3eZR/1cTJSLChf6w1HgMCY6BSywb52DGYXV0npUbYrIkh/Hsye1oL9aPNJ0hArG0I0ZoBDlDrlgTHVGyfk1PLhG2yEZozes29JjYFT8EtBuqMCXrB/AfrQlUZM1PteYJ1gA4jvGO2R7SWtC9cBZmNY=
  on:
    all_branches: true
