language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: 'evening-hollows-42255'
  api_key:
    secure: Tmh8et09X/3cqeRn/h9Tn7xftgQwUVnFiTCA8FL4Wbz+mrPtTqzVL2FjWWB/8E85dcZCS0oL6Z/Nq4MaiMKe+psXZ2leOOo5pPjEhYLtLDepK5GvgMP7QWISp8tfa1lWwbgVUJy2CkMOFcqkKDSi6P/tsCtmg2au6nf3drskCXnW/G8Rwem/pNxaYyihuMrMTyHcFT0/soTemE2kHJG1aIlbphLdM0/tkfpoorQ1/Xhmvyp72PL4WpX+L/n2Ey2squyQ0t7fM5rpRp6IKEYEii+7Kb8dddQGDZSE0VXeq20p4pIkbfIFZ4S2YEVr2fGyQQEutNsiogPUWHFWe3C1jWFJ7t6NinAxr1aqGRSuFk4NMgckCR/Ai6EvHuvlIk7CqFF8Jw06V8FxgynauImsmbpugf2VqVkcFoF3uF4Iz41HchoDSsrt+8MFOMBa1hL85DyLN5iuEwJKjw/iMkQyw2qdlyKURmvpSl5X4rEtJm73ek7JWrU6KmpkoqKmhkPr9Eq7+9kE+/kBWnyCBaCLIrxR75DkWmRV64XQxFECPyO2Ax3kMG76yTA2+QNooVn4yOp6MH8slpLm/u5I1auATStXVvFy5LTqE4q8bZbXu9arnh1D5khUOpMQNYjKjmOOYlaoCG3ueKsOWlIieRcuOKOV1AuS7SCd4yt4j6AL2cw=
  on:
    all_branches: true
